[features]
seeds = false

# [programs.devnet]
# solana_confessions = "77rnDjSqMH4HPd4cKNV5ditDEA4zVBBpznKqpjPjeodH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/theoroque/.config/solana/cli/key.json"
